/**
 * Blueprint: Real Agent Skeleton
 * A real AI agent with Observe → Think → Act → Loop reasoning cycle.
 * The LLM decides which tool to use at each step based on context.
 *
 * Generated by agentari0 — agente skill
 * Uses Cloudflare Agents SDK + OpenAI tool use
 */

import { Agent } from "agents";
import OpenAI from "openai";

export interface Env {
  OPENAI_API_KEY: string;
  NOTION_TOKEN: string;
  NOTION_DATABASE_ID: string;
  PUSHOVER_TOKEN: string;
  PUSHOVER_USER: string;
  // APIFY_TOKEN: string;
}

// Define the tools the agent can choose from
// The LLM reads these descriptions to decide which tool to use
const TOOLS: OpenAI.Chat.ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "search_information",
      description:
        "Search for information from external sources. Use this first to gather data.",
      parameters: {
        type: "object",
        properties: {
          query: { type: "string", description: "What to search for" },
          source: {
            type: "string",
            enum: ["rss", "web", "twitter"],
            description: "Which source to use",
          },
        },
        required: ["query", "source"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "check_memory",
      description:
        "Check what this agent has done in previous runs. Use to avoid repeating content.",
      parameters: {
        type: "object",
        properties: {
          key: { type: "string", description: "What memory to retrieve" },
        },
        required: ["key"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "save_result",
      description:
        "Save the final result to Notion. Only use when you have a complete, quality result.",
      parameters: {
        type: "object",
        properties: {
          title: { type: "string" },
          content: { type: "string" },
        },
        required: ["title", "content"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "send_notification",
      description:
        "Send a push notification to the user. Only use when the result is genuinely relevant and new.",
      parameters: {
        type: "object",
        properties: {
          message: { type: "string" },
          title: { type: "string" },
        },
        required: ["message", "title"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "done",
      description:
        "Signal that the agent has completed its goal. Call this when done, even if nothing relevant was found.",
      parameters: {
        type: "object",
        properties: {
          reason: {
            type: "string",
            description: "Why the agent is done",
          },
        },
        required: ["reason"],
      },
    },
  },
];

export class MyAgent extends Agent<Env> {
  async run(): Promise<void> {
    const openai = new OpenAI({ apiKey: this.env.OPENAI_API_KEY });

    // The agent's goal — customize this for your use case
    const systemPrompt = `
You are an intelligent agent. Your goal is: [DESCRIBE YOUR AGENT'S GOAL HERE]

Rules:
- Always check your memory first to avoid repeating what you did yesterday
- If one source fails, try another
- Only call send_notification if you found something genuinely new and relevant
- If nothing relevant today, call done without notifying — don't bother the user
- When your goal is achieved, call done

Think step by step. Use tools one at a time.
    `.trim();

    const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
      { role: "system", content: systemPrompt },
      { role: "user", content: "Start working on your goal now." },
    ];

    const MAX_ITERATIONS = 10; // safety limit
    let iteration = 0;

    // THE REASONING LOOP — Observe → Think → Act → Repeat
    while (iteration < MAX_ITERATIONS) {
      iteration++;
      console.log(`[Agent] Iteration ${iteration}`);

      const response = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages,
        tools: TOOLS,
        tool_choice: "auto",
      });

      const choice = response.choices[0];
      messages.push(choice.message);

      // Agent decided it's done
      if (choice.finish_reason === "stop") {
        console.log("[Agent] Finished via natural stop");
        break;
      }

      // Agent chose a tool — execute it
      if (choice.finish_reason === "tool_calls" && choice.message.tool_calls) {
        for (const toolCall of choice.message.tool_calls) {
          const args = JSON.parse(toolCall.function.arguments);
          console.log(`[Agent] Using tool: ${toolCall.function.name}`, args);

          let result: string;

          switch (toolCall.function.name) {
            case "search_information":
              result = await this.searchInformation(args.query, args.source);
              break;
            case "check_memory":
              result = await this.checkMemory(args.key);
              break;
            case "save_result":
              await this.saveResult(args.title, args.content);
              result = "Result saved to Notion successfully.";
              break;
            case "send_notification":
              await this.sendNotification(args.message, args.title);
              result = "Notification sent successfully.";
              break;
            case "done":
              console.log(`[Agent] Done: ${args.reason}`);
              await this.updateMemory("lastRun", new Date().toISOString());
              return;
            default:
              result = `Unknown tool: ${toolCall.function.name}`;
          }

          // Feed the tool result back into the conversation
          messages.push({
            role: "tool",
            content: result,
            tool_call_id: toolCall.id,
          });
        }
      }
    }

    console.log("[Agent] Reached max iterations — stopping");
  }

  // Tool implementations — customize these for your use case

  private async searchInformation(query: string, source: string): Promise<string> {
    // TODO: implement actual search based on source
    // Use fragments from _shared/blueprints/fragments/
    return `[Searched ${source} for "${query}" — replace with real implementation]`;
  }

  private async checkMemory(key: string): Promise<string> {
    const state = await this.getState<Record<string, string>>();
    return state?.[key] ?? "No memory found for this key.";
  }

  private async updateMemory(key: string, value: string): Promise<void> {
    const state = (await this.getState<Record<string, string>>()) ?? {};
    state[key] = value;
    await this.setState(state);
  }

  private async saveResult(title: string, content: string): Promise<void> {
    // TODO: use save-notion.ts fragment from _shared/blueprints/fragments/
    console.log(`[Agent] Saving to Notion: ${title}`);
  }

  private async sendNotification(message: string, title: string): Promise<void> {
    // TODO: use notify.ts fragment from _shared/blueprints/fragments/
    console.log(`[Agent] Sending notification: ${title}`);
  }
}

// Cloudflare Worker entry point
export default {
  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    const agent = new MyAgent(env);
    ctx.waitUntil(agent.run());
  },

  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    if (request.method === "POST" && new URL(request.url).pathname === "/run") {
      const agent = new MyAgent(env);
      ctx.waitUntil(agent.run());
      return new Response(JSON.stringify({ ok: true, message: "Agent started" }), {
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response("agentari0 agent — POST /run to trigger", { status: 200 });
  },
};
