/**
 * Blueprint: Pipeline Base
 * Base skeleton for any scheduled automation on Cloudflare Workers.
 * Replace the step comments with your actual logic using fragments from _shared/blueprints/fragments/
 *
 * Generated by agentari0 — automatizacion skill
 */

export interface Env {
  // Add your environment variables here — they match your .dev.vars keys
  OPENAI_API_KEY: string;
  NOTION_TOKEN: string;
  NOTION_DATABASE_ID: string;
  PUSHOVER_TOKEN: string;
  PUSHOVER_USER: string;
  // APIFY_TOKEN: string;  // uncomment if scraping JS sites
}

export default {
  // Scheduled trigger — runs automatically on the defined cron
  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    console.log("Pipeline started:", new Date().toISOString());

    try {
      // STEP 1: Get information from source
      // const data = await scrapeStatic("https://example.com/news");
      // const data = await scrapeRSS("https://example.com/feed.xml");
      // const data = await scrapeTwitter("your search query", 20, env);

      // STEP 2: Process with AI
      // const summary = await llmSummarize(data, YOUR_SYSTEM_PROMPT, env);

      // STEP 3: Save result
      // await saveToNotion(summary, `Results ${new Date().toLocaleDateString()}`, env);

      // STEP 4: Notify
      // await notifyPushover(summary, "Your automation ran ✅", env);

      console.log("Pipeline completed successfully");
    } catch (error) {
      console.error("Pipeline error:", error);
      // Optionally notify on error:
      // await notifyPushover(`Error: ${error}`, "⚠️ Pipeline failed", env);
    }
  },

  // HTTP trigger — lets you run manually via curl or browser
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    if (request.method === "POST" && new URL(request.url).pathname === "/run") {
      ctx.waitUntil(this.scheduled({} as ScheduledEvent, env, ctx));
      return new Response(JSON.stringify({ ok: true, message: "Pipeline triggered" }), {
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response("agentari0 pipeline — POST /run to trigger", { status: 200 });
  },
};
